### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by wnikola** [js-samuraji/hello-world#6]
We should change the background color from #ffffff to something more interesting.

**Comment by nenad-abramovic** [comment]
I agree. I will assign you to this issue if you are interested.

**Comment by nenad-abramovic** [comment]
I see that you already assigned yourself.

**Comment by nenad-abramovic** [comment]
When you do a Pull Request add `Closing #6` in description to automatically close this issue.

**Comment by wnikola** [comment]
> When you do a Pull Request add `Closes #6` in description to automatically close this issue.

Will do!

**Comment by nenad-abramovic** [comment]
Assigne me to do a Code Review when you do a PR.

**Comment by nenad-abramovic** [comment]
I will now lock conversation.
